services:
  app_pg_utokyo:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.pg_utokyo
    environment:
      CONNECTION_URI: $APP_PG_UTOKYO_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_PG_UTOKYO_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_PG_UTOKYO_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_PG_UTOKYO_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 6040:8080
